---
exclude_patterns:
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.pb.go"
  - "**/service/importer/assets/*.go"
  - "**/cmd/service/assets/*.go"
  - "**/Dockerfile"
  - "**/cmd/service/tests"
  - "**/docs"
