#!/bin/bash

echo "Building mesg/core:local..."
docker build -t mesg/core:local --build-arg version="local" .

# create a symlink for system services.
rm -rf ~/.mesg/systemservices
mkdir -p ~/.mesg
ln -s $GOPATH/src/github.com/mesg-foundation/core/systemservices/_sources ~/.mesg/systemservices

# chain these to stop execution on failure.
./dev-cli stop && \
./dev-cli start && \
./dev-cli logs

./dev-cli stop