#!/bin/bash -e

VERSION="local"
LDFLAGS="-X 'github.com/mesg-foundation/core/version.Version=$VERSION'"

go build -o ./bin/cli -ldflags="$LDFLAGS" interface/cli/main.go

mesg_port=50052
endpoint="localhost:$mesg_port"
if [[ $DOCKER_HOST != "" ]]; then
  endpoint="$(echo $DOCKER_HOST | awk '{while ( match($0,/([0-9]+\.){3}[0-9]+/) ) { print substr($0,RSTART,RLENGTH); $0=substr($0,RSTART+RLENGTH) } }'):$mesg_port"
fi
MESG_CLIENT_ADDRESS=$endpoint ./bin/cli $@
