# base Go image version.
FROM golang:1.13.0-stretch AS build

WORKDIR /project

# install dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /project/e2e
CMD ["go", "test", "-v", "--run", "Execution"]
