#!/bin/bash

mesgcontainer=$(docker ps -f name=mesg-core -q)
if [ -z "$mesgcontainer" ]; then
  docker build -t mesg-core .
  docker run \
    --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/.mesg:/mesg \
    -p 50052:50052 \
    -e MESG.PATH=$HOME/.mesg \
    --name=mesg-core \
    $@ mesg-core
fi
