#!/bin/bash

mesgcontainer=$(docker ps -f name=mesg-core -q)
if [ -z "$mesgcontainer" ]; then
  docker run \
    --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/.mesg:/mesg \
    -p 50052:50052 \
    -e API.SERVICE.SOCKETPATH=$HOME/.mesg/server.sock \
    --name=mesg-core \
    $@ mesg-core
fi
