// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/runner/internal/types/msg.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_mesg_foundation_engine_hash "github.com/mesg-foundation/engine/hash"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// The message to create a Runner.
type MsgCreate struct {
	// The Runner's owner.
	Owner github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=owner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"owner,omitempty" validate:"required,accaddress"`
	// Service's hash to start the runner with.
	ServiceHash github_com_mesg_foundation_engine_hash.Hash `protobuf:"bytes,2,opt,name=serviceHash,proto3,customtype=github.com/mesg-foundation/engine/hash.Hash" json:"serviceHash" validate:"required,hash"`
	// Environmental variables to start the runner with.
	EnvHash              github_com_mesg_foundation_engine_hash.Hash `protobuf:"bytes,3,opt,name=envHash,proto3,customtype=github.com/mesg-foundation/engine/hash.Hash" json:"envHash" validate:"omitempty,hash"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *MsgCreate) Reset()         { *m = MsgCreate{} }
func (m *MsgCreate) String() string { return proto.CompactTextString(m) }
func (*MsgCreate) ProtoMessage()    {}
func (*MsgCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0041db5ef7393ba5, []int{0}
}
func (m *MsgCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreate.Unmarshal(m, b)
}
func (m *MsgCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreate.Marshal(b, m, deterministic)
}
func (m *MsgCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreate.Merge(m, src)
}
func (m *MsgCreate) XXX_Size() int {
	return xxx_messageInfo_MsgCreate.Size(m)
}
func (m *MsgCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreate proto.InternalMessageInfo

func (m *MsgCreate) GetOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Owner
	}
	return nil
}

// The message to delete a Runner.
type MsgDelete struct {
	// The Runner's owner.
	Owner github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=owner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"owner,omitempty" validate:"required,accaddress"`
	// Runner's hash
	Hash                 github_com_mesg_foundation_engine_hash.Hash `protobuf:"bytes,2,opt,name=hash,proto3,customtype=github.com/mesg-foundation/engine/hash.Hash" json:"hash" validate:"required,hash"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *MsgDelete) Reset()         { *m = MsgDelete{} }
func (m *MsgDelete) String() string { return proto.CompactTextString(m) }
func (*MsgDelete) ProtoMessage()    {}
func (*MsgDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_0041db5ef7393ba5, []int{1}
}
func (m *MsgDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDelete.Unmarshal(m, b)
}
func (m *MsgDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDelete.Marshal(b, m, deterministic)
}
func (m *MsgDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelete.Merge(m, src)
}
func (m *MsgDelete) XXX_Size() int {
	return xxx_messageInfo_MsgDelete.Size(m)
}
func (m *MsgDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelete.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelete proto.InternalMessageInfo

func (m *MsgDelete) GetOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Owner
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgCreate)(nil), "mesg.runner.types.MsgCreate")
	proto.RegisterType((*MsgDelete)(nil), "mesg.runner.types.MsgDelete")
}

func init() { proto.RegisterFile("x/runner/internal/types/msg.proto", fileDescriptor_0041db5ef7393ba5) }

var fileDescriptor_0041db5ef7393ba5 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x69, 0xf9, 0x27, 0x02, 0x0b, 0x99, 0x0a, 0x03, 0x81, 0x4c, 0x48, 0x50, 0x7b, 0x60,
	0x02, 0xa6, 0x16, 0x06, 0x16, 0x04, 0x2a, 0x1b, 0x9b, 0x6b, 0x5f, 0x1d, 0x43, 0x6d, 0xb7, 0x3e,
	0x27, 0xd0, 0x37, 0xe4, 0x05, 0x58, 0x40, 0xca, 0x43, 0x74, 0x64, 0x42, 0x71, 0x8a, 0xe8, 0x00,
	0x42, 0x42, 0x82, 0xc9, 0x3e, 0x9d, 0xbf, 0xef, 0x77, 0xfe, 0x74, 0xd1, 0xde, 0x23, 0x75, 0xb9,
	0x31, 0xe0, 0xa8, 0x32, 0x1e, 0x9c, 0x61, 0x43, 0xea, 0x27, 0x23, 0x40, 0xaa, 0x51, 0x92, 0x91,
	0xb3, 0xde, 0xc6, 0x9b, 0x1a, 0x50, 0x92, 0xfa, 0x15, 0x09, 0xcd, 0xed, 0x54, 0x5a, 0x69, 0x69,
	0x68, 0xf7, 0xf3, 0x01, 0xad, 0xaa, 0x50, 0x84, 0x5b, 0x2d, 0x4b, 0x9f, 0x9b, 0xd1, 0xda, 0x25,
	0xca, 0x33, 0x07, 0xcc, 0x43, 0xac, 0xa2, 0x65, 0xfb, 0x60, 0xc0, 0xb5, 0x1a, 0xbb, 0x8d, 0xfd,
	0x8d, 0xee, 0xcd, 0xb4, 0x4c, 0x76, 0x0a, 0x36, 0x54, 0x82, 0x79, 0x38, 0x49, 0x1d, 0x8c, 0x73,
	0xe5, 0x40, 0x1c, 0x32, 0xce, 0x99, 0x10, 0x0e, 0x10, 0xd3, 0xb7, 0x32, 0x69, 0x4b, 0xe5, 0xb3,
	0xbc, 0x4f, 0xb8, 0xd5, 0x94, 0x5b, 0xd4, 0x16, 0x67, 0x47, 0x1b, 0xc5, 0x7d, 0x3d, 0x27, 0xe9,
	0x70, 0xde, 0xa9, 0x15, 0xbd, 0x9a, 0x10, 0x8f, 0xa3, 0x75, 0x04, 0x57, 0x28, 0x0e, 0x17, 0x0c,
	0xb3, 0x56, 0x33, 0x00, 0xaf, 0x9e, 0xca, 0x64, 0xe1, 0xa5, 0x4c, 0x0e, 0xe6, 0x2c, 0xab, 0x7f,
	0xb5, 0x07, 0x36, 0x37, 0x82, 0x79, 0x65, 0x0d, 0x05, 0x23, 0x95, 0x01, 0x9a, 0x31, 0xcc, 0x48,
	0x25, 0x9d, 0x96, 0x49, 0xeb, 0x8b, 0x19, 0xab, 0x7e, 0xda, 0x9b, 0x67, 0xc4, 0x77, 0xd1, 0x2a,
	0x98, 0x22, 0xe0, 0x16, 0x03, 0xee, 0xfa, 0x77, 0xb8, 0xad, 0x4f, 0x9c, 0xd5, 0xca, 0x83, 0x1e,
	0xf9, 0xc9, 0x8c, 0xf7, 0x01, 0x48, 0x5f, 0x1b, 0x21, 0xd7, 0x73, 0x18, 0xc2, 0xff, 0xe6, 0xca,
	0xa3, 0xa5, 0xec, 0x0f, 0x03, 0x0d, 0xe6, 0xdd, 0xd3, 0xdb, 0xe3, 0x9f, 0x0d, 0xbf, 0xd9, 0xd9,
	0xfe, 0x4a, 0xd8, 0xbc, 0xa3, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xbe, 0x4b, 0xad, 0xd5,
	0x02, 0x00, 0x00,
}
