{
 "title": "Executions",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Executions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "mesg_execution_created", "legendFormat": "Created" },
    { "expr": "mesg_execution_in_progress", "legendFormat": "In Progress" },
    { "expr": "mesg_execution_updated", "legendFormat": "Updated" },
    { "expr": "mesg_execution_completed", "legendFormat": "Completed" }
   ]
  },
  {
   "title": "Executions / 1min",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mesg_execution_created[1m])",
     "legendFormat": "Created"
    },
    {
     "expr": "rate(mesg_execution_in_progress[1m])",
     "legendFormat": "In Progress"
    },
    {
     "expr": "rate(mesg_execution_updated[1m])",
     "legendFormat": "Updated"
    },
    {
     "expr": "rate(mesg_execution_completed[1m])",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "tendermint_mempool_size", "legendFormat": "Mempool" },
    { "expr": "tendermint_consensus_num_txs", "legendFormat": "Consensus" },
    { "expr": "tendermint_mempool_failed_txs", "legendFormat": "Total Failed" },
    { "expr": "tendermint_consensus_total_txs", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes",
     "legendFormat": "Block size"
    }
   ]
  }
 ]
}