// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/definition/execution.proto

package definition

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Status represents the status of a single execution.
// Note that a valid execution must have only one status
// flag at time.
type Status int32

const (
	// Unknown status represents any status unknown to execution.
	Status_Unknown Status = 0
	// Created is an initial status after execution creation.
	Status_Created Status = 1
	// InProgress informs that processing of execution has been started.
	Status_InProgress Status = 2
	// Completed is a success status after execution was processed.
	Status_Completed Status = 3
	// Failed is an error status after execution was processed.
	Status_Failed Status = 4
)

var Status_name = map[int32]string{
	0: "Unknown",
	1: "Created",
	2: "InProgress",
	3: "Completed",
	4: "Failed",
}

var Status_value = map[string]int32{
	"Unknown":    0,
	"Created":    1,
	"InProgress": 2,
	"Completed":  3,
	"Failed":     4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4855769b4238a396, []int{0}
}

// Execution represents a single execution run in engine.
type Execution struct {
	// Hash is a unique hash to identify execution.
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// parentHash is the unique hash of parent execution. if execution is triggered by another one, dependency execution considered as the parent.
	ParentHash string `protobuf:"bytes,2,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	// eventID is unique event id.
	EventID string `protobuf:"bytes,3,opt,name=eventID,proto3" json:"eventID,omitempty"`
	// Status is the current status of execution.
	Status Status `protobuf:"varint,4,opt,name=status,proto3,enum=definition.Status" json:"status,omitempty"`
	// instanceHash is hash of the instance that can proceed an execution
	InstanceHash string `protobuf:"bytes,5,opt,name=instanceHash,proto3" json:"instanceHash,omitempty"`
	// taskKey is the key of the task of this execution.
	TaskKey string `protobuf:"bytes,6,opt,name=taskKey,proto3" json:"taskKey,omitempty"`
	// inputs data of the execution.
	Inputs string `protobuf:"bytes,7,opt,name=inputs,proto3" json:"inputs,omitempty"`
	// outputs are the returned data of successful execution.
	Outputs string `protobuf:"bytes,8,opt,name=outputs,proto3" json:"outputs,omitempty"`
	// error message of a failed execution.
	Error string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	// tags are optionally associated with execution by the user.
	Tags                 []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Execution) Reset()         { *m = Execution{} }
func (m *Execution) String() string { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()    {}
func (*Execution) Descriptor() ([]byte, []int) {
	return fileDescriptor_4855769b4238a396, []int{0}
}

func (m *Execution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution.Unmarshal(m, b)
}
func (m *Execution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution.Marshal(b, m, deterministic)
}
func (m *Execution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution.Merge(m, src)
}
func (m *Execution) XXX_Size() int {
	return xxx_messageInfo_Execution.Size(m)
}
func (m *Execution) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution.DiscardUnknown(m)
}

var xxx_messageInfo_Execution proto.InternalMessageInfo

func (m *Execution) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Execution) GetParentHash() string {
	if m != nil {
		return m.ParentHash
	}
	return ""
}

func (m *Execution) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func (m *Execution) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Unknown
}

func (m *Execution) GetInstanceHash() string {
	if m != nil {
		return m.InstanceHash
	}
	return ""
}

func (m *Execution) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

func (m *Execution) GetInputs() string {
	if m != nil {
		return m.Inputs
	}
	return ""
}

func (m *Execution) GetOutputs() string {
	if m != nil {
		return m.Outputs
	}
	return ""
}

func (m *Execution) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Execution) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterEnum("definition.Status", Status_name, Status_value)
	proto.RegisterType((*Execution)(nil), "definition.Execution")
}

func init() {
	proto.RegisterFile("protobuf/definition/execution.proto", fileDescriptor_4855769b4238a396)
}

var fileDescriptor_4855769b4238a396 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x7f, 0x52, 0x33, 0x6a, 0x09, 0x83, 0xc8, 0x5e, 0x49, 0xa9, 0x37, 0xa5, 0x60,
	0x02, 0x16, 0x5f, 0xc0, 0xaa, 0x58, 0x44, 0x90, 0x8a, 0x37, 0xde, 0x6d, 0x93, 0x69, 0x1a, 0xda,
	0xee, 0x86, 0xfd, 0xf1, 0xe7, 0x69, 0x7c, 0x55, 0xd9, 0x4d, 0x4a, 0x15, 0xbc, 0x3b, 0xe7, 0x7c,
	0x99, 0x9c, 0x1d, 0x06, 0x2e, 0x2a, 0x25, 0x8d, 0x5c, 0xd8, 0x65, 0x9a, 0xd3, 0xb2, 0x14, 0xa5,
	0x29, 0xa5, 0x48, 0xe9, 0x93, 0x32, 0xeb, 0x54, 0xe2, 0x29, 0xc2, 0x9e, 0x0d, 0xbf, 0x5b, 0x10,
	0xdd, 0xed, 0x38, 0x22, 0x74, 0x56, 0x5c, 0xaf, 0x58, 0x30, 0x08, 0x46, 0xd1, 0xdc, 0x6b, 0x3c,
	0x07, 0xa8, 0xb8, 0x22, 0x61, 0x1e, 0x1c, 0x69, 0x79, 0xf2, 0x2b, 0x41, 0x06, 0x3d, 0x7a, 0x27,
	0x61, 0x66, 0xb7, 0xac, 0xed, 0xe1, 0xce, 0xe2, 0x18, 0x42, 0x6d, 0xb8, 0xb1, 0x9a, 0x75, 0x06,
	0xc1, 0xa8, 0x7f, 0x85, 0xc9, 0xbe, 0x38, 0x79, 0xf1, 0x64, 0xde, 0x7c, 0x81, 0x43, 0x38, 0x2e,
	0x85, 0x36, 0x5c, 0x64, 0xe4, 0x7b, 0xba, 0xfe, 0x57, 0x7f, 0x32, 0xd7, 0x64, 0xb8, 0x5e, 0x3f,
	0xd2, 0x17, 0x0b, 0xeb, 0xa6, 0xc6, 0xe2, 0x19, 0x84, 0xa5, 0xa8, 0xac, 0xd1, 0xac, 0xe7, 0x41,
	0xe3, 0xdc, 0x84, 0xb4, 0xc6, 0x83, 0xc3, 0x7a, 0xa2, 0xb1, 0x78, 0x0a, 0x5d, 0x52, 0x4a, 0x2a,
	0x16, 0xf9, 0xbc, 0x36, 0x6e, 0x7f, 0xc3, 0x0b, 0xcd, 0x60, 0xd0, 0x76, 0xfb, 0x3b, 0x3d, 0x7e,
	0x82, 0xb0, 0x7e, 0x2b, 0x1e, 0x41, 0xef, 0x55, 0xac, 0x85, 0xfc, 0x10, 0xf1, 0x81, 0x33, 0x53,
	0x45, 0xdc, 0x50, 0x1e, 0x07, 0xd8, 0x07, 0x98, 0x89, 0x67, 0x25, 0x0b, 0x45, 0x5a, 0xc7, 0x2d,
	0x3c, 0x81, 0x68, 0x2a, 0xb7, 0xd5, 0x86, 0x1c, 0x6e, 0x23, 0x40, 0x78, 0xcf, 0xcb, 0x0d, 0xe5,
	0x71, 0xe7, 0xe6, 0xfa, 0x6d, 0x52, 0x94, 0x66, 0x65, 0x17, 0x49, 0x26, 0xb7, 0xe9, 0x96, 0x74,
	0x71, 0xb9, 0x94, 0x56, 0xe4, 0xdc, 0x9f, 0x2a, 0x93, 0x8a, 0xd2, 0x7f, 0x6e, 0xb8, 0x08, 0x7d,
	0x38, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x04, 0x40, 0xb7, 0xe1, 0x01, 0x00, 0x00,
}
