// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protobuf/api/instance.proto

package api

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	instance "github.com/mesg-foundation/engine/instance"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// The request's data for the `Get` API.
type GetInstanceRequest struct {
	Hash                 github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=hash,proto3,customtype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"hash" validate:"required,hash"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *GetInstanceRequest) Reset()         { *m = GetInstanceRequest{} }
func (m *GetInstanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetInstanceRequest) ProtoMessage()    {}
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d44b8f4a870f63, []int{0}
}
func (m *GetInstanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstanceRequest.Unmarshal(m, b)
}
func (m *GetInstanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstanceRequest.Marshal(b, m, deterministic)
}
func (m *GetInstanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstanceRequest.Merge(m, src)
}
func (m *GetInstanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetInstanceRequest.Size(m)
}
func (m *GetInstanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstanceRequest proto.InternalMessageInfo

// The request's data for the `List` API.
type ListInstanceRequest struct {
	// Filter used to filter a list of instance.
	Filter               *ListInstanceRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListInstanceRequest) Reset()         { *m = ListInstanceRequest{} }
func (m *ListInstanceRequest) String() string { return proto.CompactTextString(m) }
func (*ListInstanceRequest) ProtoMessage()    {}
func (*ListInstanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d44b8f4a870f63, []int{1}
}
func (m *ListInstanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInstanceRequest.Unmarshal(m, b)
}
func (m *ListInstanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInstanceRequest.Marshal(b, m, deterministic)
}
func (m *ListInstanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInstanceRequest.Merge(m, src)
}
func (m *ListInstanceRequest) XXX_Size() int {
	return xxx_messageInfo_ListInstanceRequest.Size(m)
}
func (m *ListInstanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInstanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListInstanceRequest proto.InternalMessageInfo

func (m *ListInstanceRequest) GetFilter() *ListInstanceRequest_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

// Filter contains filtering criteria.
type ListInstanceRequest_Filter struct {
	// Service hash to filter executions.
	ServiceHash          github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=serviceHash,proto3,customtype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"serviceHash" validate:"omitempty,hash"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *ListInstanceRequest_Filter) Reset()         { *m = ListInstanceRequest_Filter{} }
func (m *ListInstanceRequest_Filter) String() string { return proto.CompactTextString(m) }
func (*ListInstanceRequest_Filter) ProtoMessage()    {}
func (*ListInstanceRequest_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d44b8f4a870f63, []int{1, 0}
}
func (m *ListInstanceRequest_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInstanceRequest_Filter.Unmarshal(m, b)
}
func (m *ListInstanceRequest_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInstanceRequest_Filter.Marshal(b, m, deterministic)
}
func (m *ListInstanceRequest_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInstanceRequest_Filter.Merge(m, src)
}
func (m *ListInstanceRequest_Filter) XXX_Size() int {
	return xxx_messageInfo_ListInstanceRequest_Filter.Size(m)
}
func (m *ListInstanceRequest_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInstanceRequest_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListInstanceRequest_Filter proto.InternalMessageInfo

// The response's data for the `List` API.
type ListInstanceResponse struct {
	// List of instances that match the request's filters.
	Instances            []*instance.Instance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListInstanceResponse) Reset()         { *m = ListInstanceResponse{} }
func (m *ListInstanceResponse) String() string { return proto.CompactTextString(m) }
func (*ListInstanceResponse) ProtoMessage()    {}
func (*ListInstanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d44b8f4a870f63, []int{2}
}
func (m *ListInstanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListInstanceResponse.Unmarshal(m, b)
}
func (m *ListInstanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListInstanceResponse.Marshal(b, m, deterministic)
}
func (m *ListInstanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListInstanceResponse.Merge(m, src)
}
func (m *ListInstanceResponse) XXX_Size() int {
	return xxx_messageInfo_ListInstanceResponse.Size(m)
}
func (m *ListInstanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListInstanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListInstanceResponse proto.InternalMessageInfo

func (m *ListInstanceResponse) GetInstances() []*instance.Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func init() {
	proto.RegisterType((*GetInstanceRequest)(nil), "mesg.api.GetInstanceRequest")
	proto.RegisterType((*ListInstanceRequest)(nil), "mesg.api.ListInstanceRequest")
	proto.RegisterType((*ListInstanceRequest_Filter)(nil), "mesg.api.ListInstanceRequest.Filter")
	proto.RegisterType((*ListInstanceResponse)(nil), "mesg.api.ListInstanceResponse")
}

func init() { proto.RegisterFile("protobuf/api/instance.proto", fileDescriptor_71d44b8f4a870f63) }

var fileDescriptor_71d44b8f4a870f63 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xb1, 0x52, 0xc2, 0x40,
	0x10, 0x25, 0x03, 0x32, 0x78, 0x58, 0x9d, 0x14, 0x18, 0x45, 0x98, 0x1b, 0x0b, 0x0a, 0x49, 0x66,
	0x62, 0xa7, 0x36, 0x50, 0x88, 0x3a, 0x36, 0xa6, 0xb4, 0x0b, 0xc9, 0x12, 0x6e, 0x24, 0xdc, 0x91,
	0xbd, 0x30, 0xc3, 0x38, 0xe3, 0x37, 0xf8, 0x59, 0xf6, 0x76, 0x16, 0x7c, 0x84, 0x5f, 0xe0, 0x70,
	0x09, 0x44, 0x05, 0x2d, 0xac, 0xee, 0xf6, 0xed, 0xdb, 0xb7, 0xfb, 0xf6, 0x8e, 0x1c, 0xca, 0x58,
	0x28, 0x31, 0x48, 0x86, 0xb6, 0x27, 0xb9, 0xcd, 0x27, 0xa8, 0xbc, 0x89, 0x0f, 0x96, 0x46, 0x69,
	0x25, 0x02, 0x0c, 0x2d, 0x4f, 0x72, 0x93, 0x85, 0x22, 0x14, 0xf6, 0x9a, 0xbb, 0x8c, 0x74, 0xa0,
	0x6f, 0x29, 0xdb, 0x6c, 0xac, 0xd3, 0x6a, 0x2e, 0x01, 0x7f, 0x88, 0xb1, 0x27, 0x42, 0xfb, 0xa0,
	0x6e, 0x32, 0xd0, 0x85, 0x69, 0x02, 0xa8, 0x28, 0x90, 0xd2, 0xc8, 0xc3, 0x51, 0xdd, 0x68, 0x19,
	0xed, 0xbd, 0xde, 0xfd, 0xeb, 0xa2, 0x59, 0x78, 0x5f, 0x34, 0x3b, 0x21, 0x57, 0xa3, 0x64, 0x60,
	0xf9, 0x22, 0xb2, 0x7d, 0x81, 0x91, 0xc0, 0xec, 0xe8, 0x60, 0xf0, 0x98, 0xca, 0x5b, 0x5d, 0xdf,
	0xef, 0x06, 0x41, 0x0c, 0x88, 0x1f, 0x8b, 0x66, 0x7d, 0xe6, 0x8d, 0x79, 0xe0, 0x29, 0x38, 0x67,
	0x31, 0x4c, 0x13, 0x1e, 0x43, 0x70, 0xba, 0xd4, 0x65, 0xae, 0x96, 0x67, 0x6f, 0x06, 0xd9, 0xbf,
	0xe3, 0xb8, 0xd1, 0xfe, 0x92, 0x94, 0x87, 0x7c, 0xac, 0x20, 0xd6, 0x03, 0x54, 0x9d, 0x13, 0x6b,
	0x65, 0xd9, 0xda, 0x42, 0xb7, 0xae, 0x34, 0xd7, 0xcd, 0x6a, 0xcc, 0x67, 0x52, 0x4e, 0x11, 0xaa,
	0x48, 0x15, 0x21, 0x9e, 0x71, 0x1f, 0xae, 0x73, 0x37, 0xee, 0x7f, 0xdd, 0x1c, 0xe4, 0x6e, 0x44,
	0xc4, 0x15, 0x44, 0x52, 0xcd, 0x33, 0x3b, 0x5f, 0xdb, 0xb0, 0x5b, 0x52, 0xfb, 0x3e, 0x25, 0x4a,
	0x31, 0x41, 0xa0, 0x0e, 0xd9, 0x5d, 0x2d, 0x1f, 0xeb, 0x46, 0xab, 0xd8, 0xae, 0x3a, 0xb5, 0xd4,
	0x58, 0xda, 0x6c, 0x5d, 0x90, 0xd3, 0x9c, 0x17, 0x83, 0x54, 0x56, 0x38, 0xbd, 0x20, 0xc5, 0x3e,
	0x28, 0x7a, 0x94, 0x6f, 0x63, 0xf3, 0xe9, 0xcc, 0xad, 0x92, 0xac, 0x40, 0xfb, 0xa4, 0xb4, 0x9c,
	0x8a, 0x36, 0xfe, 0xdc, 0xa5, 0x79, 0xfc, 0x5b, 0x3a, 0x35, 0xc1, 0x0a, 0xbd, 0x9d, 0x87, 0xa2,
	0x27, 0xf9, 0xa0, 0xac, 0xff, 0xcf, 0xd9, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0xc0, 0x2a,
	0x5f, 0xab, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InstanceClient is the client API for Instance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InstanceClient interface {
	// Get returns an Instance matching the criteria of the request.
	Get(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*instance.Instance, error)
	// List returns all Instances matching the criteria of the request.
	List(ctx context.Context, in *ListInstanceRequest, opts ...grpc.CallOption) (*ListInstanceResponse, error)
}

type instanceClient struct {
	cc *grpc.ClientConn
}

func NewInstanceClient(cc *grpc.ClientConn) InstanceClient {
	return &instanceClient{cc}
}

func (c *instanceClient) Get(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*instance.Instance, error) {
	out := new(instance.Instance)
	err := c.cc.Invoke(ctx, "/mesg.api.Instance/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceClient) List(ctx context.Context, in *ListInstanceRequest, opts ...grpc.CallOption) (*ListInstanceResponse, error) {
	out := new(ListInstanceResponse)
	err := c.cc.Invoke(ctx, "/mesg.api.Instance/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstanceServer is the server API for Instance service.
type InstanceServer interface {
	// Get returns an Instance matching the criteria of the request.
	Get(context.Context, *GetInstanceRequest) (*instance.Instance, error)
	// List returns all Instances matching the criteria of the request.
	List(context.Context, *ListInstanceRequest) (*ListInstanceResponse, error)
}

// UnimplementedInstanceServer can be embedded to have forward compatible implementations.
type UnimplementedInstanceServer struct {
}

func (*UnimplementedInstanceServer) Get(ctx context.Context, req *GetInstanceRequest) (*instance.Instance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedInstanceServer) List(ctx context.Context, req *ListInstanceRequest) (*ListInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterInstanceServer(s *grpc.Server, srv InstanceServer) {
	s.RegisterService(&_Instance_serviceDesc, srv)
}

func _Instance_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mesg.api.Instance/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).Get(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Instance_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mesg.api.Instance/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServer).List(ctx, req.(*ListInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Instance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mesg.api.Instance",
	HandlerType: (*InstanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Instance_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Instance_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/api/instance.proto",
}
