/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from "web3/eth/contract";
import { TransactionObject, BlockType } from "web3/eth/types";
import { EventEmitter } from "events";
import { Provider } from "web3/providers";
import { EventData } from "web3-eth-contract/types";

export class Marketplace {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  // _address: string;
  options: contractOptions;
  methods: {
    services(arg0: string | number[]): TransactionObject<string>;

    servicesList(arg0: number | string): TransactionObject<string>;

    isPauser(account: string): TransactionObject<boolean>;

    hashToService(arg0: string | number[]): TransactionObject<string>;

    servicesVersionsListLength(
      sid: string | number[]
    ): TransactionObject<string>;

    servicesVersionsList(
      sid: string | number[],
      versionIndex: number | string
    ): TransactionObject<string>;

    servicesVersion(
      sid: string | number[],
      hash: string | number[]
    ): TransactionObject<{
      manifest: string;
      manifestProtocol: string;
      0: string;
      1: string;
    }>;

    servicesOffersLength(sid: string | number[]): TransactionObject<string>;

    servicesOffer(
      sid: string | number[],
      offerIndex: number | string
    ): TransactionObject<{
      price: string;
      duration: string;
      active: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;

    servicesPurchasesListLength(
      sid: string | number[]
    ): TransactionObject<string>;

    servicesPurchasesList(
      sid: string | number[],
      purchaseIndex: number | string
    ): TransactionObject<string>;

    servicesPurchases(
      sid: string | number[],
      purchaser: string
    ): TransactionObject<string>;

    isAuthorized(sid: string | number[]): TransactionObject<boolean>;

    unpause(): TransactionObject<void>;

    renouncePauser(): TransactionObject<void>;

    renounceOwnership(): TransactionObject<void>;

    addPauser(account: string): TransactionObject<void>;

    pause(): TransactionObject<void>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    createService(sid: string | number[]): TransactionObject<void>;

    transferServiceOwnership(
      sid: string | number[],
      newOwner: string
    ): TransactionObject<void>;

    createServiceVersion(
      sid: string | number[],
      hash: string | number[],
      manifest: (string | number[])[],
      manifestProtocol: (string | number[])[]
    ): TransactionObject<void>;

    createServiceOffer(
      sid: string | number[],
      price: number | string,
      duration: number | string
    ): TransactionObject<string>;

    disableServiceOffer(
      sid: string | number[],
      offerIndex: number | string
    ): TransactionObject<void>;

    purchase(
      sid: string | number[],
      offerIndex: number | string
    ): TransactionObject<void>;

    paused(): TransactionObject<boolean>;
    owner(): TransactionObject<string>;
    isOwner(): TransactionObject<boolean>;
    token(): TransactionObject<string>;
    servicesListLength(): TransactionObject<string>;
  };
  // deploy(options: {
  //   data: string;
  //   arguments: any[];
  // }): TransactionObject<Contract>;
  events: {
    ServiceCreated(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    ServiceOwnershipTransferred(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    ServiceVersionCreated(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    ServiceOfferCreated(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    ServiceOfferDisabled(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    ServicePurchased(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    Paused(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    Unpaused(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    PauserAdded(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    PauserRemoved(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    OwnershipTransferred(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      }
    ) => EventEmitter;
  };
  getPastEvents(
    event: string,
    options?: {
      filter?: object;
      fromBlock?: BlockType;
      toBlock?: BlockType;
      topics?: (null | string)[];
    }
  ): Promise<EventData[]>;
  // setProvider(provider: Provider): void;
  clone(): Marketplace;
}
