// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: server/grpc/orchestrator/orchestrator.proto

package orchestrator

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_mesg_foundation_engine_hash "github.com/mesg-foundation/engine/hash"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Logs returns a stream of events that satisfy specified filter.
type OrchestratorLogsRequest struct {
	// process hashes to listen the log from. If empty, logs from all processes will be returned.
	ProcessHashes        []github_com_mesg_foundation_engine_hash.Hash `protobuf:"bytes,1,rep,name=processHashes,proto3,casttype=github.com/mesg-foundation/engine/hash.Hash" json:"processHashes,omitempty" validate:"dive,required,hash"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *OrchestratorLogsRequest) Reset()         { *m = OrchestratorLogsRequest{} }
func (m *OrchestratorLogsRequest) String() string { return proto.CompactTextString(m) }
func (*OrchestratorLogsRequest) ProtoMessage()    {}
func (*OrchestratorLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bec0dafbca643bfb, []int{0}
}
func (m *OrchestratorLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrchestratorLogsRequest.Unmarshal(m, b)
}
func (m *OrchestratorLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrchestratorLogsRequest.Marshal(b, m, deterministic)
}
func (m *OrchestratorLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrchestratorLogsRequest.Merge(m, src)
}
func (m *OrchestratorLogsRequest) XXX_Size() int {
	return xxx_messageInfo_OrchestratorLogsRequest.Size(m)
}
func (m *OrchestratorLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrchestratorLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrchestratorLogsRequest proto.InternalMessageInfo

func (m *OrchestratorLogsRequest) GetProcessHashes() []github_com_mesg_foundation_engine_hash.Hash {
	if m != nil {
		return m.ProcessHashes
	}
	return nil
}

// OrchestratorLogsResponse is the message send on the Logs stream.
type OrchestratorLogsResponse struct {
	// Hash of the process
	ProcessHash github_com_mesg_foundation_engine_hash.Hash `protobuf:"bytes,1,opt,name=processHash,proto3,casttype=github.com/mesg-foundation/engine/hash.Hash" json:"processHash,omitempty"`
	// Key of the node being executed.
	NodeKey string `protobuf:"bytes,2,opt,name=nodeKey,proto3" json:"nodeKey,omitempty"`
	// Type of the node being executed.
	NodeType string `protobuf:"bytes,3,opt,name=nodeType,proto3" json:"nodeType,omitempty"`
	// Hash of the event that trigger this node. Can be empty.
	EventHash github_com_mesg_foundation_engine_hash.Hash `protobuf:"bytes,4,opt,name=eventHash,proto3,casttype=github.com/mesg-foundation/engine/hash.Hash" json:"eventHash,omitempty"`
	// Hash of the parent execution that trigger this node. Can be empty.
	ParentHash github_com_mesg_foundation_engine_hash.Hash `protobuf:"bytes,5,opt,name=parentHash,proto3,casttype=github.com/mesg-foundation/engine/hash.Hash" json:"parentHash,omitempty"`
	// Message of this log. Can be empty if error is set.
	Msg string `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	// Error message that occurred.
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// Hash of the execution created by this process. Can be empty.
	CreatedExecHash      github_com_mesg_foundation_engine_hash.Hash `protobuf:"bytes,8,opt,name=createdExecHash,proto3,casttype=github.com/mesg-foundation/engine/hash.Hash" json:"createdExecHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *OrchestratorLogsResponse) Reset()         { *m = OrchestratorLogsResponse{} }
func (m *OrchestratorLogsResponse) String() string { return proto.CompactTextString(m) }
func (*OrchestratorLogsResponse) ProtoMessage()    {}
func (*OrchestratorLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bec0dafbca643bfb, []int{1}
}
func (m *OrchestratorLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrchestratorLogsResponse.Unmarshal(m, b)
}
func (m *OrchestratorLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrchestratorLogsResponse.Marshal(b, m, deterministic)
}
func (m *OrchestratorLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrchestratorLogsResponse.Merge(m, src)
}
func (m *OrchestratorLogsResponse) XXX_Size() int {
	return xxx_messageInfo_OrchestratorLogsResponse.Size(m)
}
func (m *OrchestratorLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrchestratorLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrchestratorLogsResponse proto.InternalMessageInfo

func (m *OrchestratorLogsResponse) GetProcessHash() github_com_mesg_foundation_engine_hash.Hash {
	if m != nil {
		return m.ProcessHash
	}
	return nil
}

func (m *OrchestratorLogsResponse) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *OrchestratorLogsResponse) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *OrchestratorLogsResponse) GetEventHash() github_com_mesg_foundation_engine_hash.Hash {
	if m != nil {
		return m.EventHash
	}
	return nil
}

func (m *OrchestratorLogsResponse) GetParentHash() github_com_mesg_foundation_engine_hash.Hash {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *OrchestratorLogsResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *OrchestratorLogsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *OrchestratorLogsResponse) GetCreatedExecHash() github_com_mesg_foundation_engine_hash.Hash {
	if m != nil {
		return m.CreatedExecHash
	}
	return nil
}

func init() {
	proto.RegisterType((*OrchestratorLogsRequest)(nil), "mesg.grpc.orchestrator.OrchestratorLogsRequest")
	proto.RegisterType((*OrchestratorLogsResponse)(nil), "mesg.grpc.orchestrator.OrchestratorLogsResponse")
}

func init() {
	proto.RegisterFile("server/grpc/orchestrator/orchestrator.proto", fileDescriptor_bec0dafbca643bfb)
}

var fileDescriptor_bec0dafbca643bfb = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xad, 0x2a, 0x7f, 0x6e, 0x5d, 0x5a, 0x96, 0xd2, 0x2e, 0x86, 0x62, 0xa3, 0x93, 0xc1, 0xae,
	0xd6, 0xb4, 0xb7, 0x96, 0x5e, 0x0c, 0x81, 0x40, 0x12, 0x9c, 0x98, 0x5c, 0x92, 0xdb, 0x5a, 0x1a,
	0xaf, 0x04, 0x91, 0x56, 0xde, 0x5d, 0x89, 0xf8, 0x90, 0x1f, 0x91, 0x3f, 0x95, 0x9f, 0xe1, 0x1f,
	0x91, 0x63, 0x4e, 0x61, 0xd7, 0x38, 0x91, 0xe3, 0x84, 0x24, 0xbe, 0xcd, 0xdb, 0x7d, 0xf3, 0xde,
	0x83, 0x99, 0x41, 0x7d, 0x05, 0xb2, 0x00, 0x49, 0xb9, 0xcc, 0x02, 0x2a, 0x64, 0x10, 0x81, 0xd2,
	0x92, 0x69, 0x21, 0x37, 0x80, 0x9f, 0x49, 0xa1, 0x05, 0xfe, 0x9e, 0x80, 0xe2, 0xbe, 0xa1, 0xfa,
	0xe5, 0xdf, 0xb6, 0xc7, 0x05, 0x17, 0xd4, 0x72, 0xa6, 0xf9, 0x8c, 0x1a, 0x64, 0x81, 0xad, 0x56,
	0xbd, 0xde, 0xb5, 0x83, 0x7e, 0x8c, 0x4b, 0x4d, 0x87, 0x82, 0xab, 0x09, 0xcc, 0x73, 0x50, 0x1a,
	0x17, 0xe8, 0x73, 0x26, 0x45, 0x00, 0x4a, 0xed, 0x33, 0x15, 0x81, 0x22, 0x4e, 0xd7, 0xed, 0xb5,
	0x46, 0xc7, 0xb7, 0xcb, 0xce, 0xcf, 0x82, 0x5d, 0xc4, 0x21, 0xd3, 0xf0, 0xd7, 0x0b, 0xe3, 0x02,
	0x06, 0x12, 0xe6, 0x79, 0x2c, 0x21, 0x1c, 0x44, 0x4c, 0x45, 0xde, 0xdd, 0xb2, 0xd3, 0xe7, 0xb1,
	0x8e, 0xf2, 0xa9, 0x1f, 0x88, 0x84, 0x9a, 0x78, 0xbf, 0x66, 0x22, 0x4f, 0x43, 0xa6, 0x63, 0x91,
	0x52, 0x48, 0x79, 0x9c, 0x02, 0x35, 0x54, 0xdf, 0x28, 0x4f, 0x36, 0x6d, 0xbc, 0x1b, 0x17, 0x91,
	0xed, 0x4c, 0x2a, 0x13, 0xa9, 0x02, 0x7c, 0x82, 0x3e, 0x95, 0xd8, 0xc4, 0xe9, 0x3a, 0xbd, 0xd6,
	0x88, 0xbe, 0xd7, 0xb1, 0xac, 0x81, 0x09, 0xaa, 0xa7, 0x22, 0x84, 0x03, 0x58, 0x90, 0x8f, 0x5d,
	0xa7, 0xd7, 0x9c, 0xac, 0x21, 0x6e, 0xa3, 0x86, 0x29, 0x4f, 0x17, 0x19, 0x10, 0xd7, 0x7e, 0x3d,
	0x60, 0x7c, 0x84, 0x9a, 0x50, 0x40, 0xaa, 0x6d, 0x8c, 0xca, 0x6e, 0x31, 0x1e, 0x15, 0xf0, 0x18,
	0xa1, 0x8c, 0xc9, 0xb5, 0x5e, 0x75, 0x37, 0xbd, 0x92, 0x04, 0xfe, 0x8a, 0xdc, 0x44, 0x71, 0x52,
	0xb3, 0xb1, 0x4d, 0x89, 0xbf, 0xa1, 0x2a, 0x48, 0x29, 0x24, 0xa9, 0xdb, 0xb7, 0x15, 0xc0, 0x67,
	0xe8, 0x4b, 0x20, 0x81, 0x69, 0x08, 0xf7, 0x2e, 0x21, 0xb0, 0xee, 0x8d, 0xdd, 0xdc, 0x9f, 0xea,
	0xfc, 0xbe, 0x42, 0xad, 0xf2, 0x1c, 0x71, 0x82, 0x2a, 0x66, 0x96, 0x98, 0xfa, 0xcf, 0x6f, 0xac,
	0xff, 0xc2, 0x26, 0xb6, 0x87, 0x6f, 0x6f, 0x58, 0xad, 0x89, 0xf7, 0x61, 0xe8, 0x8c, 0xfe, 0x9f,
	0xff, 0x7b, 0x3d, 0xbe, 0x39, 0xb4, 0x38, 0x80, 0xed, 0x4b, 0x9b, 0xd6, 0xec, 0x85, 0xfc, 0xb9,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x1c, 0x67, 0xcd, 0x8c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrchestratorClient interface {
	// Logs returns a stream of events that satisfy criteria specified.
	Logs(ctx context.Context, in *OrchestratorLogsRequest, opts ...grpc.CallOption) (Orchestrator_LogsClient, error)
}

type orchestratorClient struct {
	cc *grpc.ClientConn
}

func NewOrchestratorClient(cc *grpc.ClientConn) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) Logs(ctx context.Context, in *OrchestratorLogsRequest, opts ...grpc.CallOption) (Orchestrator_LogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Orchestrator_serviceDesc.Streams[0], "/mesg.grpc.orchestrator.Orchestrator/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Orchestrator_LogsClient interface {
	Recv() (*OrchestratorLogsResponse, error)
	grpc.ClientStream
}

type orchestratorLogsClient struct {
	grpc.ClientStream
}

func (x *orchestratorLogsClient) Recv() (*OrchestratorLogsResponse, error) {
	m := new(OrchestratorLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrchestratorServer is the server API for Orchestrator service.
type OrchestratorServer interface {
	// Logs returns a stream of events that satisfy criteria specified.
	Logs(*OrchestratorLogsRequest, Orchestrator_LogsServer) error
}

// UnimplementedOrchestratorServer can be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (*UnimplementedOrchestratorServer) Logs(req *OrchestratorLogsRequest, srv Orchestrator_LogsServer) error {
	return status.Errorf(codes.Unimplemented, "method Logs not implemented")
}

func RegisterOrchestratorServer(s *grpc.Server, srv OrchestratorServer) {
	s.RegisterService(&_Orchestrator_serviceDesc, srv)
}

func _Orchestrator_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrchestratorLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).Logs(m, &orchestratorLogsServer{stream})
}

type Orchestrator_LogsServer interface {
	Send(*OrchestratorLogsResponse) error
	grpc.ServerStream
}

type orchestratorLogsServer struct {
	grpc.ServerStream
}

func (x *orchestratorLogsServer) Send(m *OrchestratorLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Orchestrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mesg.grpc.orchestrator.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _Orchestrator_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server/grpc/orchestrator/orchestrator.proto",
}
